name: publish the package

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          registry-url: 'https://npm.pkg.github.com'
      - run: npm ci
        env:
          # Logs in into github packages
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # This will run the build process due to the "prepare" script
      - run: npm publish
        env:
          # Logs in into github packages
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
